### ISSUE TITLE
Save current position button

### ISSUE THREAD

**Issue by githubtd01** [emlid/ReachView#2]

**Comment by egorf** [comment]
Hi!

Do you mean into the base station coordinates?

**Comment by githubtd01** [comment]
Hi!,
no, I know that you already working on that.

I mean a possibility to save the current position of the rover via ReachView. So a possiblity to enter a name "point001" and save the position. So I could easyly use my smartphone to map GCPs. Or is their a better way which I miss?

The solution to add a manual switch (instead of the flash sync) doesn't give the possibility to add a name.

**Comment by egorf** [comment]
Well, at this point there is no other way of doing this. What about post-processing the logs for extracting GCPs? Or you want to have those in real time?

**Comment by githubtd01** [comment]
Hi!
I guess a combination of both. I see that it is a good solution to post process the file and the additional effort to identify the points isn't that high.

But having a quick and dirty but anyhow far better solution than my standard GPSMap 62 would also be nice. We would use that for vegetation mapping in the field (not remote sensing) and +-50cm accuracy would be far better than +-5m. But I would not need +-10cm accuracy.

Isn't it just a 15 min job to code a button which saves the current coordinates + name shown in ReachView into a csv file? I think that would be nice. Maybe also useless, I do not know that because I'm a noobie. So don't hesitate to give me a hint where I can RTFM or that I should RTFM ;-).

**Comment by egorf** [comment]
Sorry for the late reply. I'll close this issue, as original ReachView is not maintained anymore.
