### ISSUE TITLE
Multiple signal messages and Galileo ephermeris message is not selectable in base mode

### ISSUE THREAD

**Issue by MichaelEFlip** [emlid/ReachView#3]
I have created a patch to support multiple signal messages and galileo ephermeris message in base mode:
https://github.com/MichaelEFlip/ReachView/commit/b96a979daf08e381e51014f3ba28981fca18cdcb

Doppler information is lost, when converting to the normal observation message.

For further improvement it would make sense to have a little description in the combo box for each message.

**Comment by egorf** [comment]
Sorry for the late reply. I'll close this issue, as original ReachView is not maintained anymore.
