### ISSUE TITLE
Config param mis-match?

### ISSUE THREAD

**Issue by dgashby** [emlid/ReachView#4]
Hi,

I'm not sure if this is an issue or not but I noticed a discrepancy between the a configuration parameter in ReachView/rtklib_configs/reach_kinematic_default.conf (master) and those supported by RTKLIB in RTKLIB/src/options.c

The config from ReachView uses stats-errratio  yet RTKLIB doesn't support this option, instead it has stats-eratio1 and stats-eratio2.

Regards,

Dean

**Comment by egorf** [comment]
Hi!

As you can see, this is not in development anymore. This version is intended to work with RTKLIB binaries provided in the source tree. RTKLIB has moved on since then, so there might be new stuff. Overall, unsupported options will just be ignored.
